ollama:
  model: "llama3.1:8b"

classifier:
  topics: ["Политика", "Наука", "Спорт", "Технологии", "Культура", "Разное"]
  temperature: 0.0
  max_attempts: 2

generator:
  model: "llama3.1:8b"
  temperature: 2.0

scraper:
  max_articles: 5

text_embedder: cointegrated/rubert-tiny2

news_sources:
  lenta:
    url: https://lenta.ru
    text_field: text
  ria:
    url: https://ria.ru
    text_field: meta_description

logging:
  name: "news_classifier"
  level: "INFO"
  file: "logs/news_classifier.log"
